# Gradle settings
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.parallel=true

# Default Minecraft version to target when `-Pminecraft` is omitted (edit version-specific settings in props/)
minecraft_version=1.21.11

# Loader Version
neoforge_version=21.11.42

# Parchment
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

## Dependencies

# Loader & Minecraft dependency
neoforge_minecraft_dependency=[1.21.11, 26.1)
neoforge_dependency=[21.11, 26.1)

# Mod dependencies
sereneseasons_neoforge=eDxStG5h
glitchcore_neoforge=6dbbrOrO

# Key mod properties
archives_name=immersive_snow_reloaded
maven_group=net.cerealcamera
id=immersive_snow_reloaded
displayname=Immersive Snow (Reloaded)
author=CerealCamera
website=https://modrinth.com/mod/immersive-snow-reloaded
issues=https://github.com/CerealCamera/Immersive-Snow-Reloaded/issues
mod_version=2.2.0
description=Small tweaks that add to Minecraft's Winter theme.
license=MIT
updater=https://api.modrinth.com/updates/immersive-snow-reloaded/forge_updates.json?neoforge_only