# Gradle settings
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.parallel=true

# Default Minecraft version to target when `-Pminecraft` is omitted (edit version-specific settings in props/)
minecraft_version=1.20.1

# Loader Versions
fabric_loader_version=0.19.3
forge_version=1.20.1-47.4.10
enabled_platforms=fabric,forge
mappings=2023.09.03

# Mod dependencies
fabric_api_version=0.92.11+1.20.1
mod_menu_version=7.2.2
sereneseasons_forge=WMrhrybF
glitchcore_forge=pYPZ5MNI
fabric_seasons=2.4.2-BETA+1.20
snowrealmagic_forge=aQw97T9l
snowrealmagic_fabric=10.7.0
kiwi_forge=11.10.3+forge
kiwi_fabric=11.10.3+fabric
vanillabackport_forge=u8YPiN39
vanillabackport_fabric=KbcStX3T
platform_forge=aWxR0Ksa
platform_fabric=kM9ocKlu

# Key mod properties
archives_name=immersive_snow_reloaded
maven_group=net.cerealcamera
id=immersive_snow_reloaded
displayname=Immersive Snow (Reloaded)
author=CerealCamera
website=https://modrinth.com/mod/immersive-snow-reloaded
issues=https://github.com/CerealCamera/Immersive-Snow-Reloaded/issues
mod_version=1.2.7
description=Small tweaks that add to Minecraft's Winter theme.
license=MIT
forge_version_dependency=47.3.0
fabric_loader_version_dependency=0.16.9
updater=https://api.modrinth.com/updates/immersive-snow-reloaded/forge_updates.json?neoforge_only