# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
group=net.cerealcamera.immersive_snow_reloaded
java_version=25
minecraft_version=26.1.2
advertised_minecraft_version=26.1

## This is the version of minecraft that the 'common' project uses
neo_form_version=26.1.2-1

# Loader versions
neoforge_version=26.2.0.6-beta
fabric_version=0.19.3

# Loader & Minecraft dependencies
fabric_minecraft_dependency=>=26.1 <26.3
neoforge_minecraft_dependency=[26.1, 26.3)
neoforge_dependency=[26.1, 26.3)
neoforge_loader_version=[4,)

# Mod dependencies
fabric_api_version=0.155.2+26.1.2
sereneseasons_fabric=26.1.2.0.3
sereneseasons_neoforge=26.1.2.0.3
glitchcore_fabric=26.1.2.0.2
glitchcore_neoforge=26.1.2.0.2
snowrealmagic_neoforge=12.2.2+neoforge
snowrealmagic_fabric=26.0.2+fabric
kiwi_neoforge=26.0.9+neoforge
kiwi_fabric=26.0.4+fabric

archives_name=immersive_snow_reloaded
maven_group=net.cerealcamera
id=immersive_snow_reloaded
displayname=Immersive Snow Reloaded
author=CerealCamera
website=https://modrinth.com/mod/immersive-snow-reloaded
issues=https://github.com/CerealCamera/Immersive-Snow-Reloaded/issues
mod_version=2.2.0
description=Small tweaks that add to Minecraft's Winter theme.
license=MIT
updater=https://api.modrinth.com/updates/immersive-snow-reloaded/forge_updates.json?neoforge_only
