pluginManagement {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven {
            url = 'https://maven.minecraftforge.net/'
            content {
                includeGroup 'de.oceanlabs.mcp'
                includeGroup 'net.minecraftforge'
            }
        }
        gradlePluginPortal()
    }
}

rootProject.name = 'Immersive-Snow-Reloaded'

include 'common'
include 'fabric'
if (providers.gradleProperty('enabled_platforms').get().split(',').contains('neoforge')) {
    include 'neoforge'
}
