architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // These are only compile-time dependencies, their classes may or may not be absent/present at runtime.
    modCompileOnly "net.neoforged:neoforge:${rootProject.neoforge_version}"

    modCompileOnly "maven.modrinth:serene-seasons:${rootProject.sereneseasons_neoforge}"
    modCompileOnly "maven.modrinth:glitchcore:${rootProject.glitchcore_neoforge}"

    compileOnly "com.electronwill.night-config:core:3.6.0"
}
