architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    compileOnly "maven.modrinth:serene-seasons:${project.sereneseasons_neoforge}"
    compileOnly "maven.modrinth:glitchcore:${project.glitchcore_neoforge}"

    compileOnly "maven.modrinth:snow-real-magic:${project.snowrealmagic_neoforge}"
    compileOnly "maven.modrinth:kiwi:${project.kiwi_neoforge}"
}
