architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // These are only compile-time dependencies, their classes may or may not be absent/present at runtime.
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    modCompileOnly "maven.modrinth:serene-seasons:${rootProject.sereneseasons_forge}"
    modCompileOnly "maven.modrinth:glitchcore:${rootProject.glitchcore_forge}"

    modCompileOnly "maven.modrinth:snow-real-magic:${rootProject.snowrealmagic_fabric}"
    modCompileOnly "maven.modrinth:kiwi:${rootProject.kiwi_fabric}"

    modCompileOnly "maven.modrinth:vanillabackport:${rootProject.vanillabackport_fabric}"

    compileOnly "com.electronwill.night-config:core:3.6.0"
}
